src/main/java/com/example/demo/bounded_context/user/controller/UserController.java, src/main/java/com/example/demo/bounded_context/user/entity/User.java, src/main/java/com/example/demo/bounded_context/user/repository/UserRepository.java, src/main/java/com/example/demo/bounded_context/user/service/UserService.java
- entity 생성
- repository 생성
- service 생성
- controller 생성
=> User 임시 생성

.github/workflows/cicd.yml, src/main/java/com/example/demo/bounded_context/user/controller/UserController.java
- aws rds 데이터베이스 생성
- aws ec2 인스턴스 생성
- ec2 docker compose 작성
- github actions cd 작성
=> github actions cd 작성

.github/workflows/cicd.yml, src/main/java/com/example/demo/bounded_context/user/controller/UserController.java
- github actions err : yml docker image 이름 수정
- 테스트 컨트롤러 작성
=> cd docker err 수정

src/main/java/com/example/demo/DemoApplication.java, src/main/java/com/example/demo/base/security/SecurityConfig.java
- cors 추가
- csrf 추가
- 모든 request 허용
`curl -X OPTIONS 'http://13.125.237.57/api/user' -H 'Origin: http://localhost:3000' -H 'Access-Control-Request-Method: POST' -v`
=> securityconfig 생성

src/main/java/com/example/demo/base/security/SecurityConfig.java, src/main/java/com/example/demo/bounded_context/user/controller/UserController.java, src/main/java/com/example/demo/bounded_context/user/entity/User.java, src/main/java/com/example/demo/bounded_context/user/service/UserService.java
- User entity 수정 
- 아이디 패스워드를 사용한 기본 회원가입 구현
- 비밀번호 암호화 사용
=> 사용자 회원가입 구현

src/main/java/com/example/demo/base/security/CustomUserDetailsService.java, src/main/java/com/example/demo/base/security/SecurityConfig.java, src/main/java/com/example/demo/bounded_context/user/repository/UserRepository.java
- UserDetailsService loadUserByname 오버라이드
- 인증 도메인 허용 도메인 구분
=> security 로그인 구현

src/main/java/com/example/demo/bounded_context/auth/controller/AuthController.java, src/main/java/com/example/demo/bounded_context/auth/dto/SignUpUserRequest.java, src/main/java/com/example/demo/bounded_context/auth/service/AuthService.java, src/main/java/com/example/demo/bounded_context/user/controller/UserController.java, src/main/java/com/example/demo/bounded_context/user/entity/User.java, src/main/java/com/example/demo/bounded_context/user/service/UserService.java
- User register API 삭제
- Auth sign-up API 구현
- 기존 service 에서 반환하던 response entity 를 controller 에서 service 반환하도록 수정
- controller 가 service exception 를 받도록 수정
- requestDto 생성
=> Auth : sign-up API 구현

.github/workflows/cicd.yml, build.gradle, src/main/java/com/example/demo/base/jwt/JwtProperties.java, src/main/java/com/example/demo/base/jwt/JwtProvider.java, src/main/java/com/example/demo/base/security/CustomUserDetailsService.java, src/main/java/com/example/demo/base/security/SecurityConfig.java, src/main/java/com/example/demo/bounded_context/auth/controller/AuthController.java, src/main/java/com/example/demo/bounded_context/auth/dto/SignInUserRequest.java, src/main/java/com/example/demo/bounded_context/auth/dto/TokenResponse.java, src/main/java/com/example/demo/bounded_context/auth/service/AuthService.java, src/main/java/com/example/demo/bounded_context/user/service/UserService.java
- jwtProperties secret 사용
- access / refresh token 생성 메서드 구현
- username/password 사용 로그인 구현
- service : 인증 객체 생성 후 loadUserByUsername 사용으로 인증 및 access / refresh token 생성
- controller : loadUserByUsername 메서드 수정으로 예외 반환
=> jwt 생성 및 sign-in 구현

src/main/java/com/example/demo/base/refresh_token/RefreshToken.java, src/main/java/com/example/demo/base/refresh_token/RefreshTokenRepository.java, src/main/java/com/example/demo/base/refresh_token/RefreshTokenService.java
- refresh token entity 생성
- refresh token 발급 재발급 메서드 구현
=> refresh token 구현

src/main/java/com/example/demo/base/jwt/JwtProvider.java, src/main/java/com/example/demo/base/security/filter/JwtTokenFilter.java
=> access token 인증 필터 구현

src/main/java/com/example/demo/base/exception/CustomException.java, src/main/java/com/example/demo/base/exception/ExceptionCode.java, src/main/java/com/example/demo/base/exception/ExceptionResponse.java, src/main/java/com/example/demo/base/exception/GlobalExceptionHandler.java, src/main/java/com/example/demo/base/jwt/JwtProvider.java, src/main/java/com/example/demo/base/refresh_token/RefreshTokenService.java, src/main/java/com/example/demo/bounded_context/account/service/AccountService.java, src/main/java/com/example/demo/bounded_context/auth/controller/AuthController.java, src/main/java/com/example/demo/bounded_context/auth/service/AuthService.java
- 강제적인 예외처리를 피하기 위한 runtime exception 사용
- 예외 이름, 상태, 메세지를 한번에 관리하기 위한 enum 사용
- @RestControllerAdvice 를 사용한 global exception 처리
- DTO로 body 구성
- 기존 controller/service가 반환하는 exception 수정
=> Exception 통합 처리 구현

src/main/java/com/example/demo/base/exception/ExceptionCode.java, src/main/java/com/example/demo/base/refresh_token/RefreshToken.java, src/main/java/com/example/demo/base/refresh_token/RefreshTokenService.java
=> refresh token 유효성 검사

build.gradle, src/main/java/com/example/demo/base/entity/BaseTimeEntity.java, src/main/java/com/example/demo/base/security/SecurityConfig.java, src/main/java/com/example/demo/base/security/SwaggerConfig.java, src/main/java/com/example/demo/base/security/filter/JwtTokenFilter.java, src/main/java/com/example/demo/bounded_context/account/entity/Account.java, src/main/java/com/example/demo/bounded_context/auth/controller/AuthController.java
- basetime entity 추가
- swagger 연동
- gradle
- SwaggerConfig
- auth api 수정
- JwtTokenFilter
- shouldNotFilter : 비인증 도메인 swagger 추가
- 예외처리 : ObjectMapper
=> basetime entity 추가, swagger 연동

src/main/java/com/example/demo/base/common/AuthConstants.java, src/main/java/com/example/demo/base/jwt/JwtProvider.java, src/main/java/com/example/demo/bounded_context/auth/controller/AuthController.java
- Auth : token API
- cookie를 사용하여 refresh token 전달 하도록 수정
- AuthConstants : auth 관련 상수 클래스 구현
=> token API request 수정

src/main/java/com/example/demo/base/blacklist_token/BlacklistToken.java, src/main/java/com/example/demo/base/blacklist_token/BlacklistTokenService.java, src/main/java/com/example/demo/bounded_context/account/controller/AccountController.java, src/main/java/com/example/demo/bounded_context/account/service/AccountService.java
- sign-out , info API : resolver, annotation 사용
=> Account : sign-out API 수정 / info API 구현

src/main/java/com/example/demo/bounded_context/questionBoard/dto/RequestQuestionBoardDto.java, src/main/java/com/example/demo/bounded_context/questionBoard/dto/ResponseQuestionBoardDto.java, src/main/java/com/example/demo/bounded_context/questionBoard/entity/QuestionBoard.java, src/main/java/com/example/demo/bounded_context/questionBoard/repository/QuestionBoardRepository.java, src/main/java/com/example/demo/bounded_context/questionBoard/service/QuestionBoardService.java
- 엔티티 구현
- 서비스 구현
- 리포지토리 구현
- dto 구현
=> questionBoard 관련 기능 구현

build.gradle, src/main/java/com/example/demo/bounded_context/account/entity/Account.java, src/main/java/com/example/demo/bounded_context/auth/controller/AuthController.java, src/main/java/com/example/demo/bounded_context/auth/dto/SignUpAccountRequest.java, src/main/java/com/example/demo/bounded_context/auth/service/AuthService.java
- Valid 사용
- Auth
- SignUpAccountRequest : 필드 검증 추가
- Service : Transaction 추가
- Controller : Valid 추가
- Entity : 데이터베이스 제약조건 추가
=> 검증 및 제약조건 추가

src/main/java/com/example/demo/bounded_context/separation/controller/SeparationController.java, src/main/java/com/example/demo/bounded_context/separation/service/SeparationService.java
=> flask 서버 연동 코드 작성

src/main/java/com/example/demo/base/exception/ExceptionCode.java, src/main/java/com/example/demo/bounded_context/account/entity/Account.java, src/main/java/com/example/demo/bounded_context/location/controller/LocationController.java, src/main/java/com/example/demo/bounded_context/location/dto/AddressRequest.java, src/main/java/com/example/demo/bounded_context/location/dto/LocationResponse.java, src/main/java/com/example/demo/bounded_context/location/entity/LampAndBattery.java, src/main/java/com/example/demo/bounded_context/location/entity/Medicine.java, src/main/java/com/example/demo/bounded_context/location/repository/LampAndBatteryRepository.java, src/main/java/com/example/demo/bounded_context/location/repository/MedicineRepository.java, src/main/java/com/example/demo/bounded_context/location/service/LocationService.java
- 폐의약품 수거함, 폐형광등 및 폐건전지 수거함 DB 추가
- 위치조회 : 
- 좌표조회 : JWT 토큰 파싱으로 유저의 위도 경도를 얻어 반경(m)과 함께 myqsl ST_Distance_Sphere native query 로 데이터 조회
- 주소조회 : 주소(광역시, 군/구) 으로 일치 데이터 조회
=> Feature location

src/main/java/com/example/demo/bounded_context/account/entity/Account.java, src/main/java/com/example/demo/bounded_context/auth/dto/SignUpAccountRequest.java, src/main/java/com/example/demo/bounded_context/auth/service/AuthService.java
- 사용자 위치 : 지역(state, city) -> 좌표(latitude, longitude)
- email 중복가능
=> signup API 수정

src/main/java/com/example/demo/base/exception/ExceptionResponse.java, src/main/java/com/example/demo/base/exception/GlobalExceptionHandler.java
=> Valid / global exception 수정

src/main/java/com/example/demo/base/exception/ExceptionCode.java, src/main/java/com/example/demo/bounded_context/category/entity/MainCategory.java, src/main/java/com/example/demo/bounded_context/separation/controller/SeparationController.java, src/main/java/com/example/demo/bounded_context/separation/dto/DetectResponse.java, src/main/java/com/example/demo/bounded_context/separation/dto/ImageRequest.java, src/main/java/com/example/demo/bounded_context/separation/dto/SolutionResponse.java, src/main/java/com/example/demo/bounded_context/separation/repository/MainCategoryRepository.java, src/main/java/com/example/demo/bounded_context/separation/service/DetectService.java, src/main/java/com/example/demo/bounded_context/separation/service/SeparationService.java, src/main/java/com/example/demo/bounded_context/separation/util/CategoryProvider.java
- application.yml : flask 서버주소 추가
- util
- flask response 를 위한 mapper
- dto
- DetectResponse : flask response (name, 
- ImgRequest : url 사용시 특수문자 인식으로 인한 도메인 인식 불가로 GET -> body 사용
- SolutionResponse : 배출방법
- service
- DetectService : flask 요청 응답
- controller
- solution : 이미지 및 키워드 배출방법 API 구현
- entity
- 데이터 입력(mysql import)를 위한 category image(외래키) 속성 false로 변경
- repository 
- 검색 
- 키워드 한글로 사용시 UTF-8 인코딩 필요 GET -> body 사용 예정
=> solution API 구현

src/main/java/com/example/demo/base/refresh_token/RefreshToken.java, src/main/java/com/example/demo/base/refresh_token/RefreshTokenRepository.java, src/main/java/com/example/demo/base/refresh_token/RefreshTokenService.java, src/main/java/com/example/demo/bounded_context/account/service/AccountService.java, src/main/java/com/example/demo/bounded_context/auth/service/AuthService.java
- refresh entity userId -> accountId 로 변경
- 사용자로 account entity 사용
- repository, service 도 수정 
- refresh service remove 함수 추가
- 로그아웃 및 회원탈퇴에 사용
=> refresh token field 수정

src/main/java/com/example/demo/bounded_context/questionBoard/dto/CreateQuestionBoardDto.java, src/main/java/com/example/demo/bounded_context/questionBoard/dto/ReadQuestionBoardDto.java, src/main/java/com/example/demo/bounded_context/questionBoard/entity/QuestionBoard.java, src/main/java/com/example/demo/bounded_context/questionBoard/service/QuestionBoardService.java
**변경사항**
- questionBoard 엔티티수정// category 컬럼삭제
- 그에따른 dto 및 service 수정
=> Feature question edit

src/main/java/com/example/demo/bounded_context/questionBoard/entity/QuestionBoard.java, src/main/java/com/example/demo/bounded_context/questionComment/controller/QuestionCommentController.java, src/main/java/com/example/demo/bounded_context/questionComment/entity/QuestionComment.java, src/main/java/com/example/demo/bounded_context/questionComment/service/QuestionCommentService.java
**변경사항**
- 채택된 댓글 컬럼 이름 변경 adopted writer id-> adopted comment id
- 댓글 cud, 채택 생성 및  테스트 완료
=> feat: qestionBoard 컬럼수정 및 Comment cud 작성

src/main/java/com/example/demo/bounded_context/questionBoard/entity/QuestionBoard.java, src/main/java/com/example/demo/bounded_context/recommendBoard/controller/RecommendBoardController.java, src/main/java/com/example/demo/bounded_context/recommendBoard/entity/RecommendBoard.java, src/main/java/com/example/demo/bounded_context/recommendBoard/repository/RecommendBoardRepository.java, src/main/java/com/example/demo/bounded_context/recommendBoard/service/RecommendBoardService.java
**변경사항**
-추천기능 추가
-이미 추천했을시 추천취소
=> feat: recommendBoard 작성

src/main/java/com/example/demo/bounded_context/questionBoard/controller/QuestionBoardController.java, src/main/java/com/example/demo/bounded_context/questionComment/controller/QuestionCommentController.java, src/main/java/com/example/demo/bounded_context/recommendBoard/controller/RecommendBoardController.java, src/main/java/com/example/demo/bounded_context/recommendBoard/repository/RecommendBoardRepository.java
**변경사항**
- recommendBoard 정상작동을 위한 수정
- 추천기능 테스트 완료
- Q&A 관련 api operation 작성
=> feat: recommendBoard 수정 및 타 controller operation작성

src/main/java/com/example/demo/base/exception/ExceptionCode.java, src/main/java/com/example/demo/bounded_context/solution/controller/SolutionController.java, src/main/java/com/example/demo/bounded_context/solution/controller/WikiController.java, src/main/java/com/example/demo/bounded_context/solution/dto/KeywordRequest.java, src/main/java/com/example/demo/bounded_context/solution/dto/SolutionResponse.java, src/main/java/com/example/demo/bounded_context/solution/dto/WasteListResponse.java, src/main/java/com/example/demo/bounded_context/solution/dto/WikiCompareResponse.java, src/main/java/com/example/demo/bounded_context/solution/dto/WikiListResponse.java, src/main/java/com/example/demo/bounded_context/solution/dto/WikiRequest.java, src/main/java/com/example/demo/bounded_context/solution/dto/WikiResponse.java, src/main/java/com/example/demo/bounded_context/solution/entity/Category.java, src/main/java/com/example/demo/bounded_context/solution/entity/Tag.java, src/main/java/com/example/demo/bounded_context/solution/entity/Waste.java, src/main/java/com/example/demo/bounded_context/solution/entity/Wiki.java, src/main/java/com/example/demo/bounded_context/solution/entity/WikiState.java, src/main/java/com/example/demo/bounded_context/solution/repository/TagRepository.java, src/main/java/com/example/demo/bounded_context/solution/repository/WasteRepository.java, src/main/java/com/example/demo/bounded_context/solution/repository/WikiRepository.java, src/main/java/com/example/demo/bounded_context/solution/service/SolutionService.java, src/main/java/com/example/demo/bounded_context/solution/service/TagService.java, src/main/java/com/example/demo/bounded_context/solution/service/WasteService.java, src/main/java/com/example/demo/bounded_context/solution/service/WikiService.java
- solution search API 생성
- wiki read / create / delete / accept/ reject API 생성
=> 배출 솔루션 및 위키 기능 개발

src/main/java/com/example/demo/bounded_context/questionBoard/controller/QuestionBoardController.java, src/main/java/com/example/demo/bounded_context/questionBoard/dto/PageQuestionBoardDto.java, src/main/java/com/example/demo/bounded_context/questionBoard/service/QuestionBoardService.java, src/main/java/com/example/demo/bounded_context/questionComment/dto/QuestionCommentResponseDto.java
**변경사항**
- dto에 생성날짜 속성추가
- 정렬기능(최신,추천,조회) 작성 및 테스트완료
=> feat: questionBoard 정렬기능 생성

src/main/java/com/example/demo/bounded_context/questionBoard/controller/QuestionBoardController.java, src/main/java/com/example/demo/bounded_context/questionBoard/dto/ReadQuestionBoardDto.java, src/main/java/com/example/demo/bounded_context/recycleBoard/controller/RecycleBoardController.java, src/main/java/com/example/demo/bounded_context/recycleBoard/dto/CreateRecycleBoardDto.java, src/main/java/com/example/demo/bounded_context/recycleBoard/dto/PageRecycleBoardDto.java, src/main/java/com/example/demo/bounded_context/recycleBoard/dto/ReadRecycleBoardDto.java, src/main/java/com/example/demo/bounded_context/recycleBoard/dto/UpdateRecycleBoardDto.java, src/main/java/com/example/demo/bounded_context/recycleBoard/entity/RecycleBoard.java, src/main/java/com/example/demo/bounded_context/recycleBoard/repository/RecycleBoardRepository.java, src/main/java/com/example/demo/bounded_context/recycleBoard/service/RecycleBoardService.java, src/main/java/com/example/demo/bounded_context/recycleComment/dto/RecycleCommentResponseDto.java, src/main/java/com/example/demo/bounded_context/recycleComment/entity/RecycleComment.java
**변경사항**
- 나눔게시판 crud, paging, 나눔여부 api 생성
- 그에따른 comment entity, dto 생성
- 각 paging api 수정
=> feat: recycleBoard api 생성 및 그에 필요한 comment 일부 생성, paging api수정

src/main/java/com/example/demo/base/blacklist_token/BlacklistTokenService.java, src/main/java/com/example/demo/base/common/HeaderProvider.java, src/main/java/com/example/demo/base/refresh_token/RefreshTokenService.java, src/main/java/com/example/demo/base/security/S3Config.java, src/main/java/com/example/demo/base/security/SecurityConfig.java, src/main/java/com/example/demo/base/security/filter/JwtTokenFilter.java, src/main/java/com/example/demo/bounded_context/account/controller/AccountController.java, src/main/java/com/example/demo/bounded_context/account/dto/AccountResponse.java, src/main/java/com/example/demo/bounded_context/account/entity/Account.java, src/main/java/com/example/demo/bounded_context/account/entity/Role.java, src/main/java/com/example/demo/bounded_context/account/service/AccountService.java, src/main/java/com/example/demo/bounded_context/account/service/AccountUseCase.java, src/main/java/com/example/demo/bounded_context/image/controller/ImageController.java, src/main/java/com/example/demo/bounded_context/image/service/S3ImageService.java, src/main/java/com/example/demo/bounded_context/solution/api/SolutionApi.java, src/main/java/com/example/demo/bounded_context/solution/controller/SolutionController.java, src/main/java/com/example/demo/bounded_context/solution/dto/ImageRequest.java, src/main/java/com/example/demo/bounded_context/solution/dto/KeywordRequest.java, src/main/java/com/example/demo/bounded_context/solution/service/DetectService.java, src/main/java/com/example/demo/bounded_context/solution/service/SolutionUseCase.java, src/main/java/com/example/demo/bounded_context/wiki/repository/WikiRepository.java, src/main/java/com/example/demo/bounded_context/wiki/service/WikiService.java, src/main/java/com/example/demo/bounded_context/wiki/service/WikiUseCase.java
- 권한 부여 및 권한에 따른 엔드포인트 구별
- account usecase, service 분리
- s3 image upload service 생성
- 회원 탈퇴 시 연관관계 연결 정리
- 검색 시 파라미터 사용, 이미지의 경우 인코딩 경로
=> Feature solution

src/main/java/com/example/demo/bounded_context/questionBoard/controller/QuestionBoardController.java, src/main/java/com/example/demo/bounded_context/questionBoard/dto/ReadQuestionBoardDto.java, src/main/java/com/example/demo/bounded_context/questionBoard/service/QuestionBoardService.java, src/main/java/com/example/demo/bounded_context/questionComment/entity/QuestionComment.java, src/main/java/com/example/demo/bounded_context/recommendComment/controller/RecommendCommentController.java, src/main/java/com/example/demo/bounded_context/recommendComment/entity/RecommendComment.java, src/main/java/com/example/demo/bounded_context/recommendComment/repository/RecommendCommentRepository.java, src/main/java/com/example/demo/bounded_context/recommendComment/service/RecommendCommentService.java, src/main/java/com/example/demo/bounded_context/recycleBoard/controller/RecycleBoardController.java, src/main/java/com/example/demo/bounded_context/recycleBoard/dto/ReadRecycleBoardDto.java, src/main/java/com/example/demo/bounded_context/recycleBoard/service/RecycleBoardService.java
**변경사항**
- Q&A 댓글 추천 api 작성
- 각 게시글 read dto에서 작성자 닉네임만 가져오도록 수정
=> feat: 댓글 추천 api 추가 및 read dto 수정

src/main/java/com/example/demo/bounded_context/questionBoard/dto/ReadQuestionBoardDto.java
**변경사항**
- 채택한 댓글이 없는 게시글 read시 뜨는 오류 수정
=> feat: Q&A readDto 오류 수정

src/main/java/com/example/demo/bounded_context/account/service/AccountUseCase.java, src/main/java/com/example/demo/bounded_context/solution/dto/DetectResponse.java, src/main/java/com/example/demo/bounded_context/solution/repository/WasteRepository.java, src/main/java/com/example/demo/bounded_context/solution/service/SolutionUseCase.java, src/main/java/com/example/demo/bounded_context/solution/service/WasteService.java, src/main/java/com/example/demo/bounded_context/solution/util/CategoryProvider.java, src/main/java/com/example/demo/bounded_context/wiki/api/WikiApi.java, src/main/java/com/example/demo/bounded_context/wiki/controller/WikiController.java, src/main/java/com/example/demo/bounded_context/wiki/dto/WikiListResponse.java, src/main/java/com/example/demo/bounded_context/wiki/repository/WikiRepository.java, src/main/java/com/example/demo/bounded_context/wiki/service/WikiService.java, src/main/java/com/example/demo/bounded_context/wiki/service/WikiUseCase.java
- account withdrawal 시 solution writer 변경 로직 추가
- waste 별 wiki list 조회 API 추가
- detect image response dto 국가 배출방법 이미지 url 추가
=> wiki list, account withdrawal, solution detect API 수정

src/main/java/com/example/demo/bounded_context/image/controller/ImageController.java, src/main/java/com/example/demo/bounded_context/location/controller/LocationController.java, src/main/java/com/example/demo/bounded_context/location/dto/LocationResponse.java, src/main/java/com/example/demo/bounded_context/solution/dto/ContributeCreationListResponse.java, src/main/java/com/example/demo/bounded_context/solution/dto/SolutionResponse.java, src/main/java/com/example/demo/bounded_context/wiki/dto/WikiListResponse.java, src/main/java/com/example/demo/bounded_context/wiki/dto/WikiResponse.java
- Location / Image API 및 dto swagger 수정
- 사용자 필드가 포함되는 솔루션 또는 위키 response 에 사용자 id 포함
=> swagger 수정

src/main/java/com/example/demo/bounded_context/account/dto/AccountResponse.java, src/main/java/com/example/demo/bounded_context/solution/dto/ContributeCreationListResponse.java, src/main/java/com/example/demo/bounded_context/solution/dto/SolutionResponse.java, src/main/java/com/example/demo/bounded_context/wiki/dto/WikiListResponse.java, src/main/java/com/example/demo/bounded_context/wiki/dto/WikiResponse.java
- account 정보를 포함하는 dto 에 accountId 필드 추가
- dto 필드 이름 수정
=> account 정보를 포함하는 dto 수정

src/main/java/com/example/demo/bounded_context/solution/service/DetectService.java, src/main/java/com/example/demo/bounded_context/wiki/api/WikiApi.java, src/main/java/com/example/demo/bounded_context/wiki/controller/WikiController.java, src/main/java/com/example/demo/bounded_context/wiki/repository/WikiRepository.java, src/main/java/com/example/demo/bounded_context/wiki/service/WikiService.java, src/main/java/com/example/demo/bounded_context/wiki/service/WikiUseCase.java
- 관리자를 위한 위키 전체 목록 조회 API 구현
- AI API 예외 메세지 수정
=> 위키 전체 목록 조회 API

src/main/java/com/example/demo/bounded_context/questionBoard/controller/QuestionBoardController.java, src/main/java/com/example/demo/bounded_context/questionBoard/entity/QuestionBoard.java, src/main/java/com/example/demo/bounded_context/questionBoard/repository/QuestionBoardRepository.java, src/main/java/com/example/demo/bounded_context/questionBoard/service/QuestionBoardService.java, src/main/java/com/example/demo/bounded_context/questionComment/entity/QuestionComment.java, src/main/java/com/example/demo/bounded_context/recycleBoard/controller/RecycleBoardController.java, src/main/java/com/example/demo/bounded_context/recycleBoard/repository/RecycleBoardRepository.java, src/main/java/com/example/demo/bounded_context/recycleBoard/service/RecycleBoardService.java
**변경사항**
- 각 게시판 제목 검색 API 추가
- 추천수가 1개이상인 게시글 삭제시 발생하는 오류 수정
=> feat: 검색 API 작성 및 삭제오류수정

src/main/java/com/example/demo/bounded_context/questionBoard/controller/QuestionBoardController.java, src/main/java/com/example/demo/bounded_context/recycleBoard/controller/RecycleBoardController.java
=> feat: 검색 API 수정

src/main/java/com/example/demo/base/security/SwaggerConfig.java
변경사항
-프론트 포기오류 고치기위한 스웨거 버전 표기
=> feat: 스웨거 버전 표기

src/main/java/com/example/demo/bounded_context/questionBoard/controller/QuestionBoardController.java, src/main/java/com/example/demo/bounded_context/questionBoard/repository/QuestionBoardRepository.java, src/main/java/com/example/demo/bounded_context/recycleBoard/controller/RecycleBoardController.java, src/main/java/com/example/demo/bounded_context/solution/controller/SolutionController.java, src/main/java/com/example/demo/bounded_context/solution/repository/WasteRepository.java, src/main/java/com/example/demo/bounded_context/solution/service/WasteService.java
**변경사항**
- 강화검색 작성 및 스웨거 작동 확인
=> feat: 강화검색 작성

src/main/java/com/example/demo/bounded_context/solution/dto/PageWasteDto.java
=> feat: pagewastedto 작성

src/main/java/com/example/demo/bounded_context/account/controller/AccountController.java, src/main/java/com/example/demo/bounded_context/account/repository/AccountRepository.java, src/main/java/com/example/demo/bounded_context/account/service/AccountService.java, src/main/java/com/example/demo/bounded_context/questionBoard/controller/QuestionBoardController.java, src/main/java/com/example/demo/bounded_context/questionBoard/entity/QuestionBoard.java, src/main/java/com/example/demo/bounded_context/questionBoard/repository/QuestionBoardRepository.java, src/main/java/com/example/demo/bounded_context/questionBoard/service/QuestionBoardService.java, src/main/java/com/example/demo/bounded_context/recycleBoard/controller/RecycleBoardController.java, src/main/java/com/example/demo/bounded_context/recycleBoard/entity/RecycleBoard.java, src/main/java/com/example/demo/bounded_context/recycleBoard/repository/RecycleBoardRepository.java, src/main/java/com/example/demo/bounded_context/recycleBoard/service/RecycleBoardService.java
**변경사항**
-닉네임,아이디,이메일 중복검사 작성
-닉네임 검색 작성 및 그에따른 각 게시판 닉네임 컬럼 추가
=> feat: 중복검사 및 닉네임 검색 작성

src/main/java/com/example/demo/bounded_context/account/controller/AccountController.java, src/main/java/com/example/demo/bounded_context/account/dto/AccountDuplicateDto.java
=> feat: 중복검사 dto 작성

src/main/java/com/example/demo/bounded_context/questionBoard/controller/QuestionBoardController.java, src/main/java/com/example/demo/bounded_context/questionBoard/service/QuestionBoardService.java
**변경사항**
-Q&A 게시글 페이징시 오래된순 옵션 추가
=> feat: 게시글 오래된순 페이징 추가

src/main/java/com/example/demo/bounded_context/image/service/S3ImageService.java
=> feat: S3주소 변경

src/main/java/com/example/demo/bounded_context/image/service/S3ImageService.java
=> feat: S3주소 변경1

src/main/java/com/example/demo/bounded_context/solution/service/DetectService.java
=> feat: S3주소 변경2

src/main/java/com/example/demo/bounded_context/declareQboard/controller/DeclareQboardController.java, src/main/java/com/example/demo/bounded_context/declareQboard/dto/DeclareQboardDto.java, src/main/java/com/example/demo/bounded_context/declareQboard/entity/DeclareQboard.java, src/main/java/com/example/demo/bounded_context/declareQboard/repository/DeclareQboardRepository.java, src/main/java/com/example/demo/bounded_context/declareQboard/service/DeclareQboardService.java, src/main/java/com/example/demo/bounded_context/declareQcomment/controller/DeclareQcommentController.java, src/main/java/com/example/demo/bounded_context/declareQcomment/dto/DeclareQcommentDto.java, src/main/java/com/example/demo/bounded_context/declareQcomment/entity/DeclareQcomment.java, src/main/java/com/example/demo/bounded_context/declareQcomment/repository/DeclareQcommentRepository.java, src/main/java/com/example/demo/bounded_context/declareQcomment/service/DeclareQcommentService.java
**변경사항**
-게시글 신고기능 추가
-댓글 신고기능 추가
-각 계정당 각 게시글 및 댓글에 한번만 신고 가능
=> feat: Q&A게시글 댓글 신고기능 추가

src/main/java/com/example/demo/bounded_context/questionBoard/entity/QuestionBoard.java, src/main/java/com/example/demo/bounded_context/questionComment/entity/QuestionComment.java
=> feat: Q&A 신고 cascade추가

src/main/java/com/example/demo/bounded_context/solution/controller/SolutionController.java
**변경사항**
-image 검색 api에  헤더값 추가
=> feat: 이미지검색 헤더추가

src/main/java/com/example/demo/base/security/SecurityConfig.java
=> feat: cors 관련 수정
